on:
  push:
  pull_request:

name: build
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run:  npm install

      - name: build all
        env:
            BUILD: true
        run:  node index.js

      - name: move files
        if: ${{ always() }}
        run:  node index.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: smart-items-${{ github.sha }}
          path: |
            items/*.zip