on:
  push:
    branches:
      - "!master"
  pull_request:

name: CI
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run:  npm install
      - name: build all
        run:  node index.js